server:
  port: 8001

dubbo:
  application:
    # 应用名称
    name: provider
  registry:
    # 注册中心地址
    address: zookeeper://10.0.0.51:2181
    timeout: 6000
  # 元数据中心地址
  metadata-report:
    address: zookeeper://10.0.0.51:2181
  protocol:
  # 协议名称
    name: dubbo
    port: 20880
  scan:
  # 扫描位置
    base-packages: com.elltor.provider.service
